Pages/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using projekt_web.Models;

namespace projekt_web.Pages
{
    public class CreateModel : PageModel, IDisposable
    {
        [BindProperty]
        public IFormFile? UploadedPdfFile { get; set; }
        [BindProperty]
        public string? DivDescriptionContent { get; set; }
        [BindProperty]
        public string? DivNameContent { get; set; }
        [BindProperty]
        public string? DivDatasheetContent {  get; set; }
        public Item Record { get; set; }

        private readonly IWebHostEnvironment _hostingEnvironment;
        private readonly IItemRepository _itemRepository;
        
        public CreateModel(IItemRepository itemRepository, IWebHostEnvironment hostingEnvironment)
        {
            if (Record == null) Record = new Item();
            _hostingEnvironment = hostingEnvironment;
            _itemRepository = itemRepository;
        }
        public void OnGet()
        {
            
        }
        // operacje na plikach - zapisywanie/usuwanie tymczasowych/stałych plików
        public IActionResult OnPostSave()
        {
            if (DivNameContent == null)
            {
                return null;
            }
            if (DivDatasheetContent != null && DivDatasheetContent.StartsWith("tmp_"))
            {
                string savedFileName = DivDatasheetContent.Substring(4);
                string uploadsFolder = Path.Combine(_hostingEnvironment.WebRootPath, "PDFs");
                string oldFilePath = Path.Combine(uploadsFolder, DivDatasheetContent);
                string newFilePath = Path.Combine(uploadsFolder, savedFileName);

                if (System.IO.File.Exists(oldFilePath))
                {
                    System.IO.File.Move(oldFilePath, newFilePath);
                    Record.Datasheet = savedFileName;
                }
            }
            Record.Description = DivDescriptionContent;
            Record.Name = DivNameContent;
            if (_itemRepository.Create(Record) == 1)
            {
                return RedirectToPage("/Index");
            }
            else
            {
                return Page();
            }

        }
        public async Task SavePdfFileAsync()
        {
            if (UploadedPdfFile != null && UploadedPdfFile.Length > 0)
            {
                string uploadsFolder = Path.Combine(_hostingEnvironment.WebRootPath, "PDFs");
                string uniqueFileName = "tmp_" + Guid.NewGuid().ToString() + "_" + UploadedPdfFile.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);

                using (FileStream stream = new FileStream(filePath, FileMode.Create))
                {
                    await UploadedPdfFile.CopyToAsync(stream);
                    Record.Datasheet = uniqueFileName;
                }
            }
        }
        public async Task<IActionResult> OnPostUploadAsync()
        {
            await SavePdfFileAsync();
            return Page(); 
        }
        public void Dispose()
        {
            //DeleteTemporaryFiles();
        }
        ~CreateModel()
        {
            Dispose();
        }
    }
}

Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace projekt_web.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Hosting.Internal;
using projekt_web.Models;
using System.Collections.ObjectModel;
using System.ComponentModel;

namespace projekt_web.Pages
{
    public class IndexModel : PageModel
    {

        public ObservableCollection<Item> Items { get; set; }
        [BindProperty]
        public string? KeyWord { get; set; } = string.Empty;
        [BindProperty]
        public string? SearchDescription { get; set; } = string.Empty;
        [BindProperty]
        public int deleteId {  get; set; }
        private readonly IWebHostEnvironment _hostingEnvironment;
        private readonly IItemRepository _itemRepository;
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger, IItemRepository itemRepository, IWebHostEnvironment hostingEnvironment)
        {
            Items = new ObservableCollection<Item>();
            Item.FillTest(Items);

            _logger = logger;
            _itemRepository = itemRepository;
            _hostingEnvironment = hostingEnvironment;

            DeleteTemporaryFiles();
        }

        public void OnGet()
        {

            if (Request.Cookies.TryGetValue("KeyWord", out string? keyword))
            {
                KeyWord = keyword;
            }
            else
            {
                KeyWord = string.Empty;
            }
            _itemRepository.SearchAll(Items, KeyWord);
        }
        public IActionResult OnPostDelete()
        {
            _itemRepository.Delete(deleteId);   
            return RedirectToPage();
        }
        public IActionResult OnPostSearch()
        {
            if (KeyWord == null) KeyWord = string.Empty;
            _itemRepository.SearchAll(Items, KeyWord);
            CookieOptions keyWordCookieOptions = new CookieOptions
            {
                HttpOnly = true,
                Secure = true,
                SameSite = SameSiteMode.Strict
            };
            Response.Cookies.Append("Keyword", KeyWord, keyWordCookieOptions);
            return RedirectToPage();
        }

        public void DeleteTemporaryFiles()
        {
            string tempFolder = Path.Combine(_hostingEnvironment.WebRootPath, "PDFs");

            if (Directory.Exists(tempFolder))
            {
                foreach (string? file in Directory.GetFiles(tempFolder, "tmp*"))
                {
                    try
                    {
                        System.IO.File.Delete(file);
                    }
                    catch (Exception ex)
                    {
                        Console.WriteLine($"Error deleting file {file}: {ex.Message}");
                    }
                }
            }
        }
    }
}

Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace projekt_web.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Pages/Update.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using projekt_web.Models;
using System.Collections.ObjectModel;

namespace projekt_web.Pages
{
    public class UpdateModel : PageModel
    {
        [BindProperty]
        public IFormFile? UploadedPdfFile { get; set; }
        [BindProperty]
        public string? DivDescriptionContent { get; set; }
        [BindProperty]
        public string? DivNameContent { get; set; }
        [BindProperty]
        public string? DivDatasheetContent { get; set; }
        [BindProperty]
        public string? DivIdContent { get; set; }
        [BindProperty(SupportsGet = true)]
        public int ItemId { get; set; }
        public Item? Record { get; set; }
        private readonly IItemRepository _itemRepository;
        private readonly IWebHostEnvironment _hostingEnvironment;
        public UpdateModel(IItemRepository itemRepository, IWebHostEnvironment hostingEnvironment)
        {
            if (Record == null) Record = new Item();
            _itemRepository = itemRepository;
            _hostingEnvironment = hostingEnvironment;
        }
        public void OnGet()
        {
            if (ItemId == 0) { ItemId = Int32.Parse(DivIdContent); }

            Record = _itemRepository.Read(ItemId);

        }
        public IActionResult OnPostSave()
        {
            Record = new Item();
            if (DivNameContent == null || DivIdContent == null )
            {
                return Page();
            }
            if (DivDatasheetContent != null && DivDatasheetContent.StartsWith("tmp_"))
            {

                string savedFileName = DivDatasheetContent.Substring(4);
                string uploadsFolder = Path.Combine(_hostingEnvironment.WebRootPath, "PDFs");
                string oldFilePath = Path.Combine(uploadsFolder, DivDatasheetContent);
                string newFilePath = Path.Combine(uploadsFolder, savedFileName);

                if (System.IO.File.Exists(oldFilePath))
                {
                    System.IO.File.Move(oldFilePath, newFilePath);
                    Record.Datasheet = savedFileName;
                }
            }
            else
            {
                Record.Datasheet = DivDatasheetContent;
            }
            Record.Description = DivDescriptionContent;
            Record.Name = DivNameContent;
            Record.Id = Int32.Parse(DivIdContent);
            if (_itemRepository.Update(Record) == 1)
            {
                return Page();
            }
            else
            {
                return Page();
            }

        }
        public async Task SavePdfFileAsync()
        {
            if (UploadedPdfFile != null && UploadedPdfFile.Length > 0)
            {
                string uploadsFolder = Path.Combine(_hostingEnvironment.WebRootPath, "PDFs");
                string uniqueFileName = "tmp_" + Guid.NewGuid().ToString() + "_" + UploadedPdfFile.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);

                using (FileStream stream = new FileStream(filePath, FileMode.Create))
                {
                    await UploadedPdfFile.CopyToAsync(stream);
                    Record.Datasheet = uniqueFileName;
                }
            }
        }
        public async Task<IActionResult> OnPostUploadAsync()
        {
            await SavePdfFileAsync();
            return Page();
        }
    }
}

Pages/View.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Hosting.Internal;
using projekt_web.Models;
using System.Reflection;

namespace projekt_web.Pages
{
    public class ViewModel : PageModel
    {
        [BindProperty(SupportsGet = true)]
        public int ItemId { get; set; }
        [BindProperty]
        public int deleteId { get; set; }
        public Item? Record { get; set; }
        private readonly IWebHostEnvironment _hostingEnvironment;
        private readonly IItemRepository _itemRepository;
        public ViewModel(IItemRepository itemRepository, IWebHostEnvironment hostingEnvironment)
        {
            _itemRepository = itemRepository; 
            _hostingEnvironment = hostingEnvironment;

        }

        public void OnGet()
        {
            Record = _itemRepository.Read(ItemId);
        }
        public IActionResult OnPostDelete()
        {
            Record = _itemRepository.Read(deleteId);
            DeleteFile();
            _itemRepository.Delete(deleteId);
            return RedirectToPage("/Index");
        }
        public void DeleteFile()
        {
            if (Record != null && Record.Datasheet != null) {
                string folder = Path.Combine(_hostingEnvironment.WebRootPath, "PDFs");
                string filePath = Path.Combine(folder, Record.Datasheet);
                System.IO.File.Delete(filePath);
            }
        }
    }
}

Pages/Create.cshtml
@page
@model projekt_web.Pages.CreateModel
@{
}
<div hidden>
    <form form asp-page-handler="Upload" id="uploadForm" method="post" enctype="multipart/form-data">
        <input id="fileInput" type="file" name="UploadedPdfFile" accept=".pdf" style="display: none;">
        <button type="submit" style="display: none;">Submit</button>
    </form>
    <form id="SaveForm" asp-page-handler="Save" method="post">
        <input type="hidden" name="divNameContent" id="divNameInput" />
        <input type="hidden" name="divDescriptionContent" id="divDescriptionInput" />
        <input type="hidden" name="divDatasheetContent" id="divDatasheetInput" />

    </form>
    <div id="divDatasheet" hidden>@(Model.Record != null ? Model.Record.Datasheet : null)</div>
</div>
<div id="wide_options" class="themed alt_bg">

    <a asp-page="/Index">
        <button class="btn themed_narrow_button">Cancel</button>
    </a>
    <button id="uploadButton" class="btn themed_narrow_button">Upload<br> PDF</button>

   
    <button name="saveButton" class="btn themed_narrow_button" onclick="SaveToDB_Create()">Create</button>
    @* <form asp-page-handler="Save" method="post">
        <button type="submit" name="saveButton" class="btn themed_narrow_button">Save</button>
    </form> *@


    <div id="update-theme-toggler" class="theme_toggler">
        <svg class="toggler_dot" id="dot"
             width="80px" height="60px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path class="filled"
                  d="M16.75 14.5C18.1307 14.5 19.25 13.3807 19.25 12C19.25 10.6193 18.1307 9.5 16.75 9.5C15.3693 9.5 14.25 10.6193 14.25 12C14.25 13.3807 15.3693 14.5 16.75 14.5Z" />

        </svg>
        <svg class="filled"
             width="80px" height="60px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">

            <path d="M2 12C2 9.23858 4.23858 7 7 7H17C19.7614 7 22 9.23858 22 12C22 14.7614 19.7614 17 17 17H7C4.23858 17 2 14.7614 2 12ZM7 8.5C5.067 8.5 3.5 10.067 3.5 12C3.5 13.933 5.067 15.5 7 15.5H17C18.933 15.5 20.5 13.933 20.5 12C20.5 10.067 18.933 8.5 17 8.5H7Z" />
        </svg>
    </div>
    <div id="update-toggler-hitbox" onclick="SwitchTheme()" onmouseover="NudgeToggler()" onmouseout="SettleToggler()"></div>
</div>

<div class="row">
    <div class="col first_col">

        
            <h1 id="nameDiv" class="view_name alt_bg" contenteditable="true">@Model.Record.Name</h1>
            <p id="descriptionDiv" class="view_desc" contenteditable="true">@Model.Record.Description</p>
            @if (Model.Record.Datasheet != null)
            {
                <embed class="second_datasheet" src="~/PDFs/@Model.Record.Datasheet" type="application/pdf">
            }
        
        <div class="filler-div"></div>

    </div>
    <div class="col second_col">

        <div class="themed datasheet-placeholder">No Datasheet Uploaded</div>

        <div class="datasheet_wrapper">
            @if (Model.Record != null)
            {
                @if (Model.Record.Datasheet != null)
                {
                    <embed class="datasheet" src="~/PDFs/@Model.Record.Datasheet" type="application/pdf">
                }
            }
        </div>
    </div>


</div>

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}
<script src="~/js/collapse.js"></script>

<div class="toast align-items-center" role="alert" aria-live="assertive" aria-atomic="true">
    <div class="d-flex">
        <div class="toast-body">
            Hello, world! This is a toast message.
        </div>
        <button type="button" class="btn-close me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
    </div>
</div>
<!-- Page content -->

<div class="main" >

    <div>
        <div id="side_section" class="side-section-wrapper themed alt_bg">
            <div class="hide_side_btn interactable" onclick="CollapseSideSection()">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-chevron-double-left" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M8.354 1.646a.5.5 0 0 1 0 .708L2.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0" />
                    <path fill-rule="evenodd" d="M12.354 1.646a.5.5 0 0 1 0 .708L6.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0" />
                </svg>
            </div>
            
            <div class="side-section themed alt_bg">
                <div class="container mt-5">
                    <form method="post" asp-page-handler="Search" class="form-inline my-2 my-lg-0">
                        <input id="search_box" asp-for="KeyWord" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                        <input asp-for="SearchDescription" class="mycheckbox" id="search_desc" type="checkbox" />
                        <label for="search_desc">search in description</label>
                        <button class="btn my-2 my-sm-0 themed_button" type="submit">Search</button>
                    </form>
                    <a asp-page="/Create">
                    <button class="btn themed_button mt-4">Create</button>
                    </a>
                    
                </div>
                
                <div class="theme_toggler">
                    <svg class="toggler_dot" id="dot" 
                        width="180px" height="60px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path class="filled"
                            d="M16.75 14.5C18.1307 14.5 19.25 13.3807 19.25 12C19.25 10.6193 18.1307 9.5 16.75 9.5C15.3693 9.5 14.25 10.6193 14.25 12C14.25 13.3807 15.3693 14.5 16.75 14.5Z" />
                        
                    </svg>
                    <svg class="filled"
                         width="180px" height="60px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                      
                        <path d="M2 12C2 9.23858 4.23858 7 7 7H17C19.7614 7 22 9.23858 22 12C22 14.7614 19.7614 17 17 17H7C4.23858 17 2 14.7614 2 12ZM7 8.5C5.067 8.5 3.5 10.067 3.5 12C3.5 13.933 5.067 15.5 7 15.5H17C18.933 15.5 20.5 13.933 20.5 12C20.5 10.067 18.933 8.5 17 8.5H7Z" />
                    </svg>
                </div>
                <div id="browse-toggler-hitbox" onclick="SwitchTheme()" onmouseover="NudgeToggler()" onmouseout="SettleToggler()"></div>
            </div>
        </div>
        <div class="side-content" id="side_content">
            <div id="show_side_btn" class="interactable" onclick="ExpandSideSection()">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-chevron-double-right" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M3.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L9.293 8 3.646 2.354a.5.5 0 0 1 0-.708" />
                    <path fill-rule="evenodd" d="M7.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L13.293 8 7.646 2.354a.5.5 0 0 1 0-.708" />
                </svg>
            </div>
             @foreach (var item in Model.Items)
            {
                
                <div 
                    id=@("card" + item.Id.ToString()) class="card themed alt_bg">
                    @* <embed src="~/PDFs/@item.Datasheet" height="375" type="application/pdf"> *@
                    

                    <div class="card-body ">
                        
                        <a asp-page="/View" asp-route-ItemId=@item.Id>
                        <h3 class="card-title fg">@item.Name</h3>
                        </a>
                        <a asp-page="/View" asp-route-ItemId=@item.Id>
                        <p class="description fg" id=@("description" + item.Id.ToString())>
                                @item.Description
                        </p>
                        </a>
                        <div class="card_chevrons">
                            <svg id=@("down_chevron" + item.Id.ToString())
                                class="interactable" onclick=@("ExpandCardDesc('" + item.Id.ToString() + "')")
                                 xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-chevron-double-down" viewBox="0 0 16 16">
                                <path fill-rule="evenodd" d="M1.646 6.646a.5.5 0 0 1 .708 0L8 12.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708" />
                                <path fill-rule="evenodd" d="M1.646 2.646a.5.5 0 0 1 .708 0L8 8.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708" />
                            </svg>
                            <svg 
                                id =@("up_chevron" + item.Id.ToString())
                                   class="interactable" onclick=@("CollapseCardDesc('" + item.Id.ToString() + "')")
                                 xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-chevron-double-up" viewBox="0 0 16 16">
                                <path fill-rule="evenodd" d="M7.646 2.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1-.708.708L8 3.707 2.354 9.354a.5.5 0 1 1-.708-.708z" />
                                <path fill-rule="evenodd" d="M7.646 6.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1-.708.708L8 7.707l-5.646 5.647a.5.5 0 0 1-.708-.708z" />
                            </svg>
                        </div>
                        <div class="card_buttons">
                            <form asp-page-handler="Delete" id=@( "deleteForm" + item.Id.ToString()) method="post" >
                                <input id="deleteInput" name="deleteId" style="display: none;" placeholder=@item.Id value= @item.Id>
                            </form>
                            @* <input type="number" id="deleteId" placeholder=@item.Id value=@item.Id hidden> *@
                            <button class="btn themed_card_button" onclick="AttemptDelete(@item.Id)" >Delete</button>
                            <a asp-page="/Update" asp-route-ItemId=@item.Id>
                            <button class="btn themed_card_button">Update</button>
                            </a>
                             <a asp-page="/View" asp-route-ItemId=@item.Id>
                            <button class="btn themed_card_button">Read</button>
                            </a>
                            
                            
                        </div>
                        
                    </div>
                    @* <div class="image_wrapper themed alt_bg">
                       
                    @if (item.Image != "")
                    {
                        <img src="~/Images/@item.Image" />
                    }

                        <div class="img_buttons">
                            <svg id=@("down_img" + item.Id.ToString())
                                 class="interactable" onclick=@("ExpandCardImg('" + item.Id.ToString() + "')")
                                 xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-double-down" viewBox="0 0 16 16">
                                <path fill-rule="evenodd" d="M1.646 6.646a.5.5 0 0 1 .708 0L8 12.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708" />
                                <path fill-rule="evenodd" d="M1.646 2.646a.5.5 0 0 1 .708 0L8 8.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708" />
                            </svg>
                            <svg id=@("up_img" + item.Id.ToString())
                                 class="interactable" onclick=@("CollapseCardImg('" + item.Id.ToString() + "')")
                                 xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-double-up" viewBox="0 0 16 16">
                                <path fill-rule="evenodd" d="M7.646 2.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1-.708.708L8 3.707 2.354 9.354a.5.5 0 1 1-.708-.708z" />
                                <path fill-rule="evenodd" d="M7.646 6.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1-.708.708L8 7.707l-5.646 5.647a.5.5 0 0 1-.708-.708z" />
                            </svg>
                        </div>
                    </div> *@
                </div>
                
            }
            
            
        </div>
        
    </div>
    
</div>

Pages/Update.cshtml
@page
@model projekt_web.Pages.UpdateModel
@{
}
<div hidden>
    <form form asp-page-handler="Upload" id="uploadForm" method="post" enctype="multipart/form-data">
        <input id="fileInput" type="file" name="UploadedPdfFile" accept=".pdf" style="display: none;">
        <button type="submit" style="display: none;">Submit</button>
    </form>
    <form id="SaveForm" asp-page-handler="Save" method="post">
        <input type="hidden" name="divNameContent" id="divNameInput" />
        <input type="hidden" name="divDescriptionContent" id="divDescriptionInput" />
        <input type="hidden" name="divDatasheetContent" id="divDatasheetInput" />
        <input type="hidden" name="divIdContent" id="divIdInput" />
    </form>
    <div id="divDatasheet" hidden>@(Model.Record != null ? Model.Record.Datasheet : null)</div>
    <div id="divId" hidden>@(Model.Record != null ? Model.Record.Id.ToString() : null)</div>
</div>


<div id="wide_options" class="themed alt_bg">
    
    <a asp-page="/View" asp-route-ItemId=@Model.Record.Id>
        <button class="btn themed_narrow_button">Read<br>Mode</button>
    </a>
    <button id="uploadButton" class="btn themed_narrow_button">Upload<br> PDF</button>
    <button name="saveButton" class="btn themed_narrow_button" onclick="SaveToDB()">Save</button>
    
    
     <div id="update-theme-toggler" class="theme_toggler" >
            <svg class="toggler_dot" id="dot" 
                width="80px" height="60px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path class="filled"
                    d="M16.75 14.5C18.1307 14.5 19.25 13.3807 19.25 12C19.25 10.6193 18.1307 9.5 16.75 9.5C15.3693 9.5 14.25 10.6193 14.25 12C14.25 13.3807 15.3693 14.5 16.75 14.5Z" />
                        
            </svg>
            <svg class="filled"
                    width="80px" height="60px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                      
                <path d="M2 12C2 9.23858 4.23858 7 7 7H17C19.7614 7 22 9.23858 22 12C22 14.7614 19.7614 17 17 17H7C4.23858 17 2 14.7614 2 12ZM7 8.5C5.067 8.5 3.5 10.067 3.5 12C3.5 13.933 5.067 15.5 7 15.5H17C18.933 15.5 20.5 13.933 20.5 12C20.5 10.067 18.933 8.5 17 8.5H7Z" />
            </svg>
     </div>
    <div id="update-toggler-hitbox" onclick="SwitchTheme()" onmouseover="NudgeToggler()" onmouseout="SettleToggler()"></div>
</div>

<div class="row">
    <div class="col first_col">
        
            @if (Model.Record != null)
            {
            <h1 id="nameDiv" class="view_name alt_bg" contenteditable="true">@Model.Record.Name</h1>
            <p id="descriptionDiv" class="view_desc" contenteditable="true">@Model.Record.Description</p>
                @if (Model.Record.Datasheet != null)
                {
                    <embed class="second_datasheet" src="~/PDFs/@Model.Record.Datasheet" type="application/pdf">
                }
            }
            <div class="filler-div"></div>
            
    </div>
    <div class="col second_col">
        <div class="datasheet_wrapper">
            <div class="themed datasheet-placeholder">No Datasheet Uploaded</div>
            @if (Model.Record != null)
            {
                @if (Model.Record.Datasheet != null)
                {
                    <embed class="datasheet" src="~/PDFs/@Model.Record.Datasheet"  type="application/pdf">
                }
            }
        </div>
    </div>


</div>
